curators:
 - alexellis
 - LucasRoesler
 - martindekov
 - utsavanand2
 - viveksyngh
 - Waterdrips

features:
 - dco_check
 - comments
 - pr_description_required
 - release_notes
 - no_newbies
 - hacktoberfest

contributing_url: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md
